export type UUID=string; export type ISODateTime=string;
export type PilotStage='IDENTITY_LAND'|'CROP_CYCLE'|'AGRONOMY_PLAN'|'SUPPLY_READINESS'|'INVESTMENT_CONTROL'|'MOBILE_OFFLINE_SYNC'|'FIELD_EXECUTION'|'MEASUREMENTS_DECISIONS'|'HARVEST_SALE_SETTLEMENT'|'TRACEABILITY_IMPACT'|'CONTROL_TOWER_REBUILD'|'COPILOT_BOUNDARY';
export const REQUIRED_PILOT_STAGES:readonly PilotStage[]=['IDENTITY_LAND','CROP_CYCLE','AGRONOMY_PLAN','SUPPLY_READINESS','INVESTMENT_CONTROL','MOBILE_OFFLINE_SYNC','FIELD_EXECUTION','MEASUREMENTS_DECISIONS','HARVEST_SALE_SETTLEMENT','TRACEABILITY_IMPACT','CONTROL_TOWER_REBUILD','COPILOT_BOUNDARY'] as const;
export type PilotEvidenceKind='TENANT_ISOLATION'|'CANONICAL_ENTITY'|'AGRONOMIC_PLAN'|'SUPPLY_SNAPSHOT'|'INVEST_CONTROL'|'OFFLINE_SYNC'|'FIELD_EVIDENCE'|'CANONICAL_EXTERNAL_FACT'|'AGRONOMIC_DECISION'|'HARVEST_SETTLEMENT'|'TRACEABILITY_PASSPORT'|'IMPACT_SNAPSHOT'|'PROJECTOR_REBUILD'|'COPILOT_BOUNDARY';
export type EvidenceOutcome='PASS'|'FAIL'|'INFO'; export type StageStatus='PASS'|'FAIL'; export type PilotStatus='ENROLLED'|'RUNNING'|'ELIGIBLE_FOR_CERTIFICATION'|'CERTIFIED'|'FAILED'|'CLOSED';
export interface PilotEnrollment { pilotId:UUID; tenantId:UUID; name:string; farmRef:string; plotRefs:readonly string[]; cycleRefs:readonly string[]; enrolledAt:ISODateTime; policyVersion:string; status:PilotStatus; }
export interface PilotEvidence { evidenceId:string; pilotId:UUID; tenantId:UUID; stage:PilotStage; kind:PilotEvidenceKind; sourceRef:string; provenanceRef:string; sourceDigestSha256:string; observedAt:ISODateTime; outcome:EvidenceOutcome; note?:string; }
export interface StageAcceptancePolicy { stage:PilotStage; requiredKinds:readonly PilotEvidenceKind[]; minimumEvidence:number; maxAgeSeconds?:number; }
export interface PilotAcceptancePolicy { version:string; requiredStages:readonly StageAcceptancePolicy[]; requireAllStages:true; requireTenantIsolation:true; requireHumanCertification:true; }
export interface StageEvaluation { stage:PilotStage; status:StageStatus; acceptedEvidenceIds:readonly string[]; rejectedEvidenceIds:readonly string[]; reasonCodes:readonly string[]; }
export interface PilotCertificationDecision { pilotId:UUID; tenantId:UUID; policyVersion:string; evaluatedAt:ISODateTime; status:'ELIGIBLE_FOR_CERTIFICATION'|'REJECTED'; stageEvaluations:readonly StageEvaluation[]; reasonCodes:readonly string[]; evidenceDigestSha256:string; decisionDigestSha256:string; }
export interface IssuePilotCertificateCommand { tenantId:UUID; pilotId:UUID; decisionDigestSha256:string; issuedByActorId:UUID; issuedAt:ISODateTime; humanAttestation:true; }
export interface PilotCertificate { certificateId:string; pilotId:UUID; tenantId:UUID; policyVersion:string; decisionDigestSha256:string; issuedByActorId:UUID; issuedAt:ISODateTime; humanAttestation:true; state:'ACTIVE'|'REVOKED'; }
export interface PilotReplayEvent { eventId:string; tenantId:UUID; pilotId:UUID; sequence:number; eventType:string; payloadDigestSha256:string; occurredAt:ISODateTime; }
export interface PilotReplayAudit { pilotId:UUID; tenantId:UUID; status:'PASS'|'FAIL'; eventCount:number; replayDigestSha256:string; reasonCodes:readonly string[]; }
