import type { CopilotAuditPort, CopilotCitation, CopilotInquiry, CopilotModelGateway, CopilotResponse, DraftSuggestion, EvidenceBundle, EvidenceCandidate, EvidenceResolverPort } from '@agroway/copilot-knowledge-contracts';
import { evaluateAuthority } from './authority.js';
import { buildCopilotPrompt } from './prompt.js';
import { validateModelOutput } from './validator.js';
export interface CopilotDeps { resolver:EvidenceResolverPort; gateway:CopilotModelGateway; audit:CopilotAuditPort; }
function responseId(q:CopilotInquiry):string{return `copr:${q.tenantId}:${q.requestId}`}
function cite(bundle:EvidenceBundle,ids:readonly string[]):readonly CopilotCitation[]{const map=new Map(bundle.items.filter(x=>x.accepted).map(x=>[x.evidenceId,x] as const));return [...new Set(ids)].sort().flatMap(id=>{const x=map.get(id);return x?[{evidenceId:id,sourceKind:x.sourceKind,sourceRef:x.sourceRef,provenanceRef:x.provenanceRef}]:[];});}
export async function runCopilot(inquiry:CopilotInquiry,candidates:readonly EvidenceCandidate[],asOf:string,deps:CopilotDeps):Promise<CopilotResponse>{
  await deps.audit.append('CopilotInquiryRequested',{requestId:inquiry.requestId,tenantId:inquiry.tenantId,mode:inquiry.mode});
  const authority=evaluateAuthority(inquiry,asOf);await deps.audit.append('CopilotPolicyEvaluated',{requestId:inquiry.requestId,allowed:authority.allowed,reasonCodes:authority.reasonCodes});
  if(!authority.allowed){await deps.audit.append('CopilotAuthorityDenied',{requestId:inquiry.requestId,reasonCodes:authority.reasonCodes});return {responseId:responseId(inquiry),requestId:inquiry.requestId,tenantId:inquiry.tenantId,status:'REFUSED',answer:'This request requires transactional authority reserved for deterministic domain services and authorized humans.',citations:[],limitations:authority.reasonCodes,createdAt:asOf};}
  const bundle=deps.resolver.resolve(inquiry,candidates,asOf);await deps.audit.append('CopilotEvidenceBundleResolved',{requestId:inquiry.requestId,bundleId:bundle.bundleId,contextHashSha256:bundle.contextHashSha256,accepted:bundle.acceptedEvidenceIds.length,rejected:bundle.rejectedEvidenceIds.length});
  for(const item of bundle.items) await deps.audit.append(item.accepted?'CopilotEvidenceItemAccepted':'CopilotEvidenceItemRejected',{requestId:inquiry.requestId,bundleId:bundle.bundleId,evidenceId:item.evidenceId,rejectionReason:item.rejectionReason});
  if(bundle.acceptedEvidenceIds.length===0){return {responseId:responseId(inquiry),requestId:inquiry.requestId,tenantId:inquiry.tenantId,status:'PARTIAL',answer:'No canonical evidence is currently available to answer this request safely.',citations:[],limitations:['NO_ACCEPTED_EVIDENCE'],contextHashSha256:bundle.contextHashSha256,createdAt:asOf};}
  const request={requestId:inquiry.requestId,tenantId:inquiry.tenantId,mode:inquiry.mode,prompt:buildCopilotPrompt(inquiry,bundle),idempotencyKey:`copilot:${inquiry.tenantId}:${inquiry.requestId}:${bundle.contextHashSha256}`,contextHashSha256:bundle.contextHashSha256,evidenceIds:bundle.acceptedEvidenceIds};
  await deps.audit.append('CopilotExecutionRequested',{requestId:inquiry.requestId,idempotencyKey:request.idempotencyKey,contextHashSha256:bundle.contextHashSha256});const output=await deps.gateway.generate(request);await deps.audit.append('CopilotModelResponseReceived',{requestId:inquiry.requestId});const failures=validateModelOutput(output,bundle,inquiry.mode);
  if(failures.length){await deps.audit.append('CopilotResponseRejected',{requestId:inquiry.requestId,failures});return {responseId:responseId(inquiry),requestId:inquiry.requestId,tenantId:inquiry.tenantId,status:'REFUSED',answer:'The generated response failed deterministic evidence validation.',citations:[],limitations:failures,contextHashSha256:bundle.contextHashSha256,createdAt:asOf};}
  const citations=cite(bundle,output.citedEvidenceIds);let draftSuggestion:DraftSuggestion|undefined;if(output.draftSuggestion){draftSuggestion={suggestionId:`draft:${inquiry.tenantId}:${inquiry.requestId}:${bundle.contextHashSha256.slice(0,12)}`,kind:output.draftSuggestion.kind,state:'DRAFT_SUGGESTION',title:output.draftSuggestion.title,body:output.draftSuggestion.body,proposedActions:output.draftSuggestion.proposedActions,requiresHumanApproval:true};await deps.audit.append('CopilotDraftSuggestionCreated',{requestId:inquiry.requestId,suggestionId:draftSuggestion.suggestionId});}
  for(const citation of citations) await deps.audit.append('CopilotCitationAttached',{requestId:inquiry.requestId,evidenceId:citation.evidenceId,sourceRef:citation.sourceRef});await deps.audit.append('CopilotResponseValidated',{requestId:inquiry.requestId,citationCount:citations.length});await deps.audit.append('CopilotAnswerPresented',{requestId:inquiry.requestId,status:'COMPLETE'});const base={responseId:responseId(inquiry),requestId:inquiry.requestId,tenantId:inquiry.tenantId,status:'COMPLETE' as const,answer:output.answer,citations,limitations:output.limitations,contextHashSha256:bundle.contextHashSha256,createdAt:asOf};return draftSuggestion?{...base,draftSuggestion}:base;
}
