import type { ControlTowerException, ExceptionSeverity, ExceptionState } from '@agroway/invest-control-contracts';

export type ExceptionDomain='AGRONOMY'|'OPERATIONS'|'SUPPLY'|'DEMAND'|'INVESTMENT'|'SYSTEM';
export type ExceptionHumanAction='ACKNOWLEDGE'|'ASSIGN'|'ADD_EVIDENCE'|'SET_ROOT_CAUSE'|'RESOLVE'|'SUPPRESS'|'REOPEN';
export type ExceptionActorType='HUMAN'|'AI';
export type ExceptionSuggestionState='DRAFT_SUGGESTION';

export interface ExceptionEvidenceRef { evidenceRef:string; kind:'FIELD'|'AGRONOMIC'|'FINANCIAL'|'SUPPLY'|'MARKET'|'SYSTEM'|'OTHER'; label:string; capturedAt:string; source:'CANONICAL'|'TECHNICAL'|'EXPERIMENTAL'|'HISTORICAL'; }
export interface ExceptionTimelineEntry { entryId:string; at:string; actorId:string; actorType:ExceptionActorType; action:ExceptionHumanAction|'CREATED'|'AI_SUGGESTED'; fromState?:ExceptionState; toState?:ExceptionState; note?:string; }
export interface ExceptionAiSuggestion { suggestionId:string; state:ExceptionSuggestionState; generatedAt:string; summary:string; proposedRootCause:string; recommendedActions:readonly string[]; evidenceRefs:readonly string[]; authority:'ADVISORY_ONLY'; }
export interface ExceptionResolutionCase { exception:ControlTowerException; domain:ExceptionDomain; ownerActorId?:string; ownerLabel?:string; slaDueAt:string; rootCause?:string; resolutionNote?:string; evidence:readonly ExceptionEvidenceRef[]; timeline:readonly ExceptionTimelineEntry[]; aiSuggestion?:ExceptionAiSuggestion; canonicalMutated:boolean; localOnly:boolean; }
export interface HumanExceptionCommand { actorId:string; actorType:'HUMAN'; action:ExceptionHumanAction; at:string; ownerActorId?:string; ownerLabel?:string; note?:string; rootCause?:string; evidence?:ExceptionEvidenceRef; }

function assertIso(value:string):void{if(!Number.isFinite(Date.parse(value)))throw new Error('INVALID_ISO_DATETIME')}
function clone<T>(value:T):T{return JSON.parse(JSON.stringify(value)) as T}
function entry(caseId:string,cmd:HumanExceptionCommand,fromState?:ExceptionState,toState?:ExceptionState):ExceptionTimelineEntry{return {entryId:`${caseId}:${cmd.action}:${cmd.at}`,at:cmd.at,actorId:cmd.actorId,actorType:'HUMAN',action:cmd.action,fromState,toState,note:cmd.note}}
export function domainForException(code:string):ExceptionDomain{if(code.startsWith('AGRONOMY_'))return 'AGRONOMY';if(code.startsWith('OPERATIONS_'))return 'OPERATIONS';if(code.startsWith('SUPPLY_'))return 'SUPPLY';if(code.startsWith('DEMAND_'))return 'DEMAND';if(code.includes('PROJECT')||code.includes('INVESTMENT')||code.includes('LEDGER')||code.includes('CAPITAL'))return 'INVESTMENT';return 'SYSTEM'}
export function severitySlaHours(severity:ExceptionSeverity):number{return severity==='CRITICAL'?8:severity==='WARNING'?48:120}
export function computeSlaDue(openedAt:string,severity:ExceptionSeverity):string{assertIso(openedAt);return new Date(Date.parse(openedAt)+severitySlaHours(severity)*3600_000).toISOString()}
export function createExceptionResolutionCase(exception:ControlTowerException,evidence:readonly ExceptionEvidenceRef[]=[],timeline:readonly ExceptionTimelineEntry[]=[]):ExceptionResolutionCase{assertIso(exception.openedAt);assertIso(exception.updatedAt);return Object.freeze({exception:clone(exception),domain:domainForException(exception.code),slaDueAt:computeSlaDue(exception.openedAt,exception.severity),evidence:clone(evidence),timeline:clone(timeline),canonicalMutated:false,localOnly:true})}
export function attachAiSuggestion(current:ExceptionResolutionCase,suggestion:Omit<ExceptionAiSuggestion,'state'|'authority'>):ExceptionResolutionCase{assertIso(suggestion.generatedAt);const ai:ExceptionAiSuggestion=Object.freeze({...clone(suggestion),state:'DRAFT_SUGGESTION',authority:'ADVISORY_ONLY'});const timeline=[...current.timeline,{entryId:`${current.exception.exceptionId}:AI_SUGGESTED:${suggestion.generatedAt}`,at:suggestion.generatedAt,actorId:'agroway-copilot',actorType:'AI' as const,action:'AI_SUGGESTED' as const,note:'Advisory suggestion generated; no canonical state mutation.'}];return Object.freeze({...current,aiSuggestion:ai,timeline,canonicalMutated:false,localOnly:true})}
function requireHuman(cmd:HumanExceptionCommand):void{if(cmd.actorType!=='HUMAN')throw new Error('HUMAN_ACTOR_REQUIRED');if(!cmd.actorId.trim())throw new Error('HUMAN_ACTOR_ID_REQUIRED');assertIso(cmd.at)}
function requireResolveEvidence(current:ExceptionResolutionCase,cmd:HumanExceptionCommand):void{const rootCause=(cmd.rootCause??current.rootCause??'').trim();const note=(cmd.note??current.resolutionNote??'').trim();if(!current.ownerActorId)throw new Error('RESOLUTION_OWNER_REQUIRED');if(!rootCause)throw new Error('RESOLUTION_ROOT_CAUSE_REQUIRED');if(current.evidence.length===0)throw new Error('RESOLUTION_EVIDENCE_REQUIRED');if(!note)throw new Error('RESOLUTION_NOTE_REQUIRED')}
export function applyHumanExceptionCommand(current:ExceptionResolutionCase,cmd:HumanExceptionCommand):ExceptionResolutionCase{requireHuman(cmd);const next=clone(current) as ExceptionResolutionCase;const before=current.exception.state;let after=before;if(cmd.action==='ASSIGN'){if(!cmd.ownerActorId?.trim()||!cmd.ownerLabel?.trim())throw new Error('ASSIGN_OWNER_REQUIRED');next.ownerActorId=cmd.ownerActorId;next.ownerLabel=cmd.ownerLabel}else if(cmd.action==='ADD_EVIDENCE'){if(!cmd.evidence)throw new Error('EVIDENCE_REQUIRED');assertIso(cmd.evidence.capturedAt);if(current.evidence.some(x=>x.evidenceRef===cmd.evidence!.evidenceRef))throw new Error('DUPLICATE_EVIDENCE_REF');next.evidence=[...current.evidence,clone(cmd.evidence)]}else if(cmd.action==='SET_ROOT_CAUSE'){if(!cmd.rootCause?.trim())throw new Error('ROOT_CAUSE_REQUIRED');next.rootCause=cmd.rootCause.trim()}else if(cmd.action==='ACKNOWLEDGE'){if(before!=='OPEN')throw new Error('ACKNOWLEDGE_REQUIRES_OPEN');after='ACKNOWLEDGED'}else if(cmd.action==='RESOLVE'){if(before!=='OPEN'&&before!=='ACKNOWLEDGED')throw new Error('RESOLVE_REQUIRES_ACTIVE_EXCEPTION');requireResolveEvidence(current,cmd);after='RESOLVED';next.rootCause=(cmd.rootCause??current.rootCause)!.trim();next.resolutionNote=(cmd.note??current.resolutionNote)!.trim()}else if(cmd.action==='SUPPRESS'){if(before==='RESOLVED')throw new Error('RESOLVED_EXCEPTION_CANNOT_BE_SUPPRESSED');if(current.exception.severity==='CRITICAL')throw new Error('CRITICAL_EXCEPTION_CANNOT_BE_SUPPRESSED');if(!cmd.note?.trim())throw new Error('SUPPRESSION_REASON_REQUIRED');after='SUPPRESSED';next.resolutionNote=cmd.note.trim()}else if(cmd.action==='REOPEN'){if(before!=='RESOLVED'&&before!=='SUPPRESSED')throw new Error('REOPEN_REQUIRES_CLOSED_EXCEPTION');after='OPEN';next.resolutionNote=undefined}next.exception={...current.exception,state:after,updatedAt:cmd.at};next.timeline=[...current.timeline,entry(current.exception.exceptionId,cmd,before,after)];next.canonicalMutated=false;next.localOnly=true;return Object.freeze(next)}
export function resolutionReadiness(current:ExceptionResolutionCase):Readonly<{ready:boolean;missing:readonly string[]}>{const missing:string[]=[];if(!current.ownerActorId)missing.push('OWNER');if(!current.rootCause?.trim())missing.push('ROOT_CAUSE');if(current.evidence.length===0)missing.push('EVIDENCE');return Object.freeze({ready:missing.length===0,missing})}
