export type SubmissionHandoffState='PREPARED'|'EXPORTED'|'ACK_PENDING';
export type SubmissionExecutionState='NOT_EXECUTED';
export type SubmissionDestination='FUTURE_DOMAIN_ADAPTER'|'FIELD_OPERATION_ADAPTER'|'FINANCE_ADAPTER'|'SUPPLY_ADAPTER';
export interface SubmissionApprovalRef{approvalId:string;approverActorId:string;approverActorType:'HUMAN';approvalDigestSha256:string;}
export interface SubmissionEvidenceRef{evidenceId:string;reviewState:'ACCEPTED_FOR_REVIEW';freshness:'FRESH'|'STALE';}
export interface ApprovedSubmissionSource{proposalId:string;tenantId:string;projectId?:string;kind:string;title:string;proposalState:'APPROVED_FOR_SUBMISSION';requiredApprovals:1|2;approvalRecords:readonly SubmissionApprovalRef[];evidence:readonly SubmissionEvidenceRef[];evidenceContextHashSha256:string;proposalDigestSha256:string;executionState:'NOT_EXECUTED';}
export interface SubmissionHandoffPacket{packetId:string;tenantId:string;proposalId:string;projectId?:string;destination:SubmissionDestination;state:SubmissionHandoffState;idempotencyKey:string;proposalDigestSha256:string;evidenceContextHashSha256:string;approvalDigests:readonly string[];packetDigestSha256:string;preparedByActorId:string;preparedByActorType:'HUMAN';preparedAt:string;exportedAt?:string;executionState:SubmissionExecutionState;canonicalMutated:false;localOnly:true;transport:'NONE'|'LOCAL_EXPORT_ONLY';}
export interface PrepareSubmissionCommand{actorId:string;actorType:'HUMAN';destination:SubmissionDestination;preparedAt:string;idempotencyKey:string;packetDigestSha256:string;}
const SHA256=/^[a-f0-9]{64}$/;const IDEMP=/^[a-zA-Z0-9:_-]{16,160}$/;
function assertDigest(v:string,c:string){if(!SHA256.test(v))throw new Error(c)}
function assertIso(v:string){if(!Number.isFinite(Date.parse(v)))throw new Error('INVALID_ISO_DATETIME')}
export function validateApprovedSubmissionSource(source:ApprovedSubmissionSource):void{if(source.proposalState!=='APPROVED_FOR_SUBMISSION')throw new Error('SUBMISSION_REQUIRES_APPROVED_PROPOSAL');if(source.executionState!=='NOT_EXECUTED')throw new Error('SOURCE_MUST_NOT_BE_EXECUTED');if(source.approvalRecords.length<source.requiredApprovals)throw new Error('REQUIRED_HUMAN_APPROVALS_MISSING');if(source.approvalRecords.some(x=>x.approverActorType!=='HUMAN'))throw new Error('AI_APPROVAL_FORBIDDEN');if(new Set(source.approvalRecords.map(x=>x.approverActorId)).size<source.requiredApprovals)throw new Error('DISTINCT_HUMAN_APPROVERS_REQUIRED');if(!source.evidence.length||source.evidence.some(x=>x.reviewState!=='ACCEPTED_FOR_REVIEW'))throw new Error('ACCEPTED_EVIDENCE_REQUIRED');assertDigest(source.proposalDigestSha256,'PROPOSAL_DIGEST_REQUIRED');assertDigest(source.evidenceContextHashSha256,'EVIDENCE_CONTEXT_HASH_REQUIRED');source.approvalRecords.forEach(x=>assertDigest(x.approvalDigestSha256,'APPROVAL_DIGEST_REQUIRED'));}
export function prepareSubmissionHandoff(source:ApprovedSubmissionSource,cmd:PrepareSubmissionCommand):SubmissionHandoffPacket{validateApprovedSubmissionSource(source);if(cmd.actorType!=='HUMAN'||!cmd.actorId.trim())throw new Error('HUMAN_PREPARER_REQUIRED');if(!IDEMP.test(cmd.idempotencyKey))throw new Error('IDEMPOTENCY_KEY_INVALID');assertDigest(cmd.packetDigestSha256,'PACKET_DIGEST_REQUIRED');assertIso(cmd.preparedAt);return Object.freeze({packetId:`handoff:${source.proposalId}:${cmd.idempotencyKey}`,tenantId:source.tenantId,proposalId:source.proposalId,projectId:source.projectId,destination:cmd.destination,state:'PREPARED',idempotencyKey:cmd.idempotencyKey,proposalDigestSha256:source.proposalDigestSha256,evidenceContextHashSha256:source.evidenceContextHashSha256,approvalDigests:source.approvalRecords.map(x=>x.approvalDigestSha256),packetDigestSha256:cmd.packetDigestSha256,preparedByActorId:cmd.actorId,preparedByActorType:'HUMAN',preparedAt:cmd.preparedAt,executionState:'NOT_EXECUTED',canonicalMutated:false,localOnly:true,transport:'NONE'});}
export function markSubmissionExported(packet:SubmissionHandoffPacket,exportedAt:string):SubmissionHandoffPacket{assertIso(exportedAt);if(packet.state!=='PREPARED')throw new Error('ONLY_PREPARED_PACKET_CAN_EXPORT');if(packet.executionState!=='NOT_EXECUTED')throw new Error('ALPHA6_EXECUTION_FORBIDDEN');return Object.freeze({...packet,state:'EXPORTED',exportedAt,transport:'LOCAL_EXPORT_ONLY',executionState:'NOT_EXECUTED',canonicalMutated:false,localOnly:true});}
export function markAckPending(packet:SubmissionHandoffPacket):SubmissionHandoffPacket{if(packet.state!=='EXPORTED')throw new Error('ACK_PENDING_REQUIRES_EXPORTED_PACKET');return Object.freeze({...packet,state:'ACK_PENDING',executionState:'NOT_EXECUTED',canonicalMutated:false,localOnly:true,transport:'LOCAL_EXPORT_ONLY'});}
export function assertNoExecution(packet:SubmissionHandoffPacket):void{if(packet.executionState!=='NOT_EXECUTED'||packet.canonicalMutated!==false)throw new Error('ALPHA6_EXECUTION_FORBIDDEN');}
