export type ControlFlowStage='EXCEPTION'|'EVIDENCE'|'APPROVAL'|'HANDOFF';
export type ControlExecutionState='NOT_EXECUTED';
export interface UnifiedControlContext{version:1;tenantId:string;exceptionId?:string|null;evidenceIds:readonly string[];proposalId?:string|null;packetId?:string|null;correlationId:string;lastStage:ControlFlowStage;updatedAt:string;authority:'HUMAN_ONLY';aiAuthority:'ADVISORY_ONLY';executionState:ControlExecutionState;canonicalMutated:false;localOnly:true;}
const ID=/^[a-zA-Z0-9:_-]{2,180}$/;
function assertId(value:string|undefined|null,code:string){if(value!=null&&!ID.test(value))throw new Error(code)}
function assertIso(value:string){if(!Number.isFinite(Date.parse(value)))throw new Error('CONTROL_FLOW_UPDATED_AT_INVALID')}
export function validateUnifiedControlContext(ctx:UnifiedControlContext):void{if(ctx.version!==1)throw new Error('CONTROL_FLOW_VERSION_UNSUPPORTED');if(!ID.test(ctx.tenantId))throw new Error('CONTROL_FLOW_TENANT_REQUIRED');assertId(ctx.exceptionId,'CONTROL_FLOW_EXCEPTION_ID_INVALID');assertId(ctx.proposalId,'CONTROL_FLOW_PROPOSAL_ID_INVALID');assertId(ctx.packetId,'CONTROL_FLOW_PACKET_ID_INVALID');ctx.evidenceIds.forEach(v=>assertId(v,'CONTROL_FLOW_EVIDENCE_ID_INVALID'));if(new Set(ctx.evidenceIds).size!==ctx.evidenceIds.length)throw new Error('CONTROL_FLOW_DUPLICATE_EVIDENCE');if(!ID.test(ctx.correlationId))throw new Error('CONTROL_FLOW_CORRELATION_REQUIRED');assertIso(ctx.updatedAt);if(ctx.authority!=='HUMAN_ONLY')throw new Error('CONTROL_FLOW_HUMAN_AUTHORITY_REQUIRED');if(ctx.aiAuthority!=='ADVISORY_ONLY')throw new Error('CONTROL_FLOW_AI_AUTHORITY_VIOLATION');if(ctx.executionState!=='NOT_EXECUTED')throw new Error('CONTROL_FLOW_EXECUTION_FORBIDDEN');if(ctx.canonicalMutated!==false)throw new Error('CONTROL_FLOW_CANONICAL_MUTATION_FORBIDDEN');if(ctx.localOnly!==true)throw new Error('CONTROL_FLOW_LOCAL_ONLY_REQUIRED');}
export function advanceControlFlow(ctx:UnifiedControlContext,stage:ControlFlowStage,updatedAt:string):UnifiedControlContext{const next={...ctx,lastStage:stage,updatedAt,executionState:'NOT_EXECUTED' as const,canonicalMutated:false as const,localOnly:true as const};validateUnifiedControlContext(next);return Object.freeze(next);}
export function bindExceptionContext(ctx:UnifiedControlContext,exceptionId:string,correlationId:string,updatedAt:string):UnifiedControlContext{const next={...ctx,exceptionId,correlationId,lastStage:'EXCEPTION' as const,updatedAt,evidenceIds:[],proposalId:null,packetId:null};validateUnifiedControlContext(next);return Object.freeze(next);}
export function bindEvidenceContext(ctx:UnifiedControlContext,evidenceIds:readonly string[],updatedAt:string):UnifiedControlContext{if(!ctx.exceptionId)throw new Error('CONTROL_FLOW_EXCEPTION_REQUIRED_BEFORE_EVIDENCE');const next={...ctx,evidenceIds:[...evidenceIds],lastStage:'EVIDENCE' as const,updatedAt};validateUnifiedControlContext(next);return Object.freeze(next);}
export function bindApprovalContext(ctx:UnifiedControlContext,proposalId:string,updatedAt:string):UnifiedControlContext{if(!ctx.exceptionId||!ctx.evidenceIds.length)throw new Error('CONTROL_FLOW_EVIDENCE_REQUIRED_BEFORE_APPROVAL');const next={...ctx,proposalId,lastStage:'APPROVAL' as const,updatedAt};validateUnifiedControlContext(next);return Object.freeze(next);}
export function bindHandoffContext(ctx:UnifiedControlContext,packetId:string,updatedAt:string):UnifiedControlContext{if(!ctx.proposalId)throw new Error('CONTROL_FLOW_APPROVAL_REQUIRED_BEFORE_HANDOFF');const next={...ctx,packetId,lastStage:'HANDOFF' as const,updatedAt,executionState:'NOT_EXECUTED' as const,canonicalMutated:false as const};validateUnifiedControlContext(next);return Object.freeze(next);}
