import type { PilotAcceptancePolicy, PilotCertificationDecision, PilotEnrollment, PilotEvidence, PilotStage, StageEvaluation } from '@agroway/pilot-certification-contracts';
import { REQUIRED_PILOT_STAGES } from '@agroway/pilot-certification-contracts';
import { sha256Canonical } from './hash.js';
const SHA=/^[a-f0-9]{64}$/;function unique<T>(xs: readonly T[]): T[]{ return [...new Set(xs)]; }function validTime(value:string):number|undefined{const t=Date.parse(value);return Number.isFinite(t)?t:undefined;}function evidenceOrder(a:PilotEvidence,b:PilotEvidence):number{return a.evidenceId.localeCompare(b.evidenceId)||sha256Canonical(a).localeCompare(sha256Canonical(b));}function runtimeFlag(policy:PilotAcceptancePolicy,key:'requireAllStages'|'requireTenantIsolation'|'requireHumanCertification'):unknown{return (policy as unknown as Record<string,unknown>)[key];}
export function evaluatePilot(enrollment:PilotEnrollment,evidence:readonly PilotEvidence[],policy:PilotAcceptancePolicy,evaluatedAt:string):PilotCertificationDecision {
  const globalReasons:string[]=[];const evaluatedMs=validTime(evaluatedAt); const enrolledMs=validTime(enrollment.enrolledAt);if(evaluatedMs===undefined) globalReasons.push('INVALID_EVALUATED_AT');if(enrolledMs===undefined) globalReasons.push('INVALID_ENROLLED_AT');if(evaluatedMs!==undefined&&enrolledMs!==undefined&&evaluatedMs<enrolledMs) globalReasons.push('EVALUATION_BEFORE_ENROLLMENT');if(!['RUNNING','ELIGIBLE_FOR_CERTIFICATION'].includes(enrollment.status)) globalReasons.push('PILOT_STATUS_NOT_EVALUATABLE');if(enrollment.policyVersion!==policy.version) globalReasons.push('POLICY_VERSION_MISMATCH');if(runtimeFlag(policy,'requireAllStages')!==true) globalReasons.push('POLICY_REQUIRE_ALL_STAGES_MUST_BE_TRUE');if(runtimeFlag(policy,'requireTenantIsolation')!==true) globalReasons.push('POLICY_TENANT_ISOLATION_MUST_BE_TRUE');if(runtimeFlag(policy,'requireHumanCertification')!==true) globalReasons.push('POLICY_HUMAN_CERTIFICATION_MUST_BE_TRUE');
  const policyStageNames=policy.requiredStages.map(s=>s.stage as string);const requiredStageSet=new Set<string>(REQUIRED_PILOT_STAGES);if(policyStageNames.length!==REQUIRED_PILOT_STAGES.length || policyStageNames.some(s=>!requiredStageSet.has(s)) || REQUIRED_PILOT_STAGES.some(s=>!policyStageNames.includes(s))) globalReasons.push('POLICY_STAGE_SET_INVALID');if(policyStageNames.length!==unique(policyStageNames).length) globalReasons.push('DUPLICATE_POLICY_STAGE');
  const evidenceCounts=new Map<string,number>();for(const item of evidence)evidenceCounts.set(item.evidenceId,(evidenceCounts.get(item.evidenceId)??0)+1);
  const stages=policy.requiredStages.map(stagePolicy=>{const accepted:string[]=[]; const rejected:string[]=[]; const reasons:string[]=[];const requiredKinds=stagePolicy.requiredKinds.map(String);if(!Number.isSafeInteger(stagePolicy.minimumEvidence)||stagePolicy.minimumEvidence<1) reasons.push('POLICY_MINIMUM_EVIDENCE_INVALID');if(requiredKinds.length===0||new Set(requiredKinds).size!==requiredKinds.length) reasons.push('POLICY_REQUIRED_KINDS_INVALID');if(stagePolicy.maxAgeSeconds!==undefined&&(!Number.isFinite(stagePolicy.maxAgeSeconds)||stagePolicy.maxAgeSeconds<0)) reasons.push('POLICY_MAX_AGE_INVALID');const stageEvidence=evidence.filter(e=>e.stage===stagePolicy.stage);for(const item of stageEvidence){let ok=true;if(!item.evidenceId.trim()){reasons.push('EVIDENCE_ID_REQUIRED');ok=false;}if((evidenceCounts.get(item.evidenceId)??0)>1){reasons.push('DUPLICATE_EVIDENCE_ID');ok=false;}if(item.tenantId!==enrollment.tenantId||item.pilotId!==enrollment.pilotId){reasons.push('TENANT_OR_PILOT_MISMATCH');ok=false;}if(!item.sourceRef.trim()||!item.provenanceRef.trim()){reasons.push('EVIDENCE_PROVENANCE_REQUIRED');ok=false;}if(!SHA.test(item.sourceDigestSha256)){reasons.push('INVALID_EVIDENCE_DIGEST');ok=false;}const observedMs=validTime(item.observedAt);if(observedMs===undefined){reasons.push('INVALID_EVIDENCE_TIMESTAMP');ok=false;}else if(evaluatedMs!==undefined){if(observedMs>evaluatedMs){reasons.push('FUTURE_EVIDENCE');ok=false;}if(stagePolicy.maxAgeSeconds!==undefined&&stagePolicy.maxAgeSeconds>=0&&(evaluatedMs-observedMs)/1000>stagePolicy.maxAgeSeconds){reasons.push('STALE_EVIDENCE');ok=false;}} else ok=false;if(item.outcome==='FAIL'){reasons.push('NEGATIVE_EVIDENCE');ok=false;}if(item.outcome==='INFO'){reasons.push('INFORMATIONAL_EVIDENCE_NOT_PROOF');ok=false;}(ok?accepted:rejected).push(item.evidenceId);}const acceptedSet=new Set(accepted);const acceptedItems=stageEvidence.filter(x=>acceptedSet.has(x.evidenceId));for(const kind of stagePolicy.requiredKinds) if(!acceptedItems.some(e=>e.kind===kind)) reasons.push(`MISSING_KIND:${kind}`);if(acceptedSet.size<stagePolicy.minimumEvidence) reasons.push('INSUFFICIENT_EVIDENCE');const uniqueReasons=unique(reasons).sort();return {stage:stagePolicy.stage,status:uniqueReasons.length?'FAIL':'PASS',acceptedEvidenceIds:[...acceptedSet].sort(),rejectedEvidenceIds:unique(rejected).sort(),reasonCodes:uniqueReasons} satisfies StageEvaluation;});
  if(stages.some(s=>s.status!=='PASS')) globalReasons.push('REQUIRED_STAGE_FAILED');const identity=stages.find(s=>s.stage==='IDENTITY_LAND');const tenantEvidence=evidence.some(e=>e.stage==='IDENTITY_LAND'&&e.kind==='TENANT_ISOLATION'&&e.outcome==='PASS'&&identity?.acceptedEvidenceIds.includes(e.evidenceId));if(!tenantEvidence) globalReasons.push('TENANT_ISOLATION_NOT_PROVEN');const orderedEvidence=[...evidence].sort(evidenceOrder);const evidenceDigestSha256=sha256Canonical(orderedEvidence);const reasonCodes=unique(globalReasons).sort();const status: PilotCertificationDecision['status']=reasonCodes.length===0?'ELIGIBLE_FOR_CERTIFICATION':'REJECTED';const base={pilotId:enrollment.pilotId,tenantId:enrollment.tenantId,policyVersion:policy.version,evaluatedAt,status,stageEvaluations:stages,reasonCodes,evidenceDigestSha256};return {...base,decisionDigestSha256:sha256Canonical(base)};
}
export function requiredPilotStages(_policy:PilotAcceptancePolicy):readonly PilotStage[]{return REQUIRED_PILOT_STAGES;}
