import http from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));const root=path.join(here,'public');const port=Number(process.env.PORT||4273);
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml'};
const headers={'cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer','x-frame-options':'DENY','permissions-policy':'geolocation=(), microphone=(), camera=()'};
function routeDocument(pathname){if(pathname==='/control'||pathname==='/control/')return{file:'home-original.html',mode:'HOME_RECOVERED'};if(pathname==='/control/projects/inv-yar-001'||pathname.startsWith('/control/projects/inv-yar-001/'))return{file:'project-original.html',mode:'PROJECT_RECOVERED'};if(pathname==='/control/authorization'||pathname.startsWith('/control/authorization/'))return{file:'authorization.html',mode:'DIRECT'};if(pathname==='/control/handoff'||pathname.startsWith('/control/handoff/'))return{file:'handoff.html',mode:'DIRECT'};if(pathname==='/control/approvals'||pathname.startsWith('/control/approvals/'))return{file:'approvals.html',mode:'DIRECT'};if(pathname==='/control/evidence'||pathname.startsWith('/control/evidence/'))return{file:'evidence.html',mode:'DIRECT'};if(pathname==='/control/exceptions'||pathname.startsWith('/control/exceptions/'))return{file:'index.html',mode:'DIRECT'};return null}
function integrateRecoveredHtml(text,mode){if(mode==='HOME_RECOVERED')return text.replace('href="/styles.css"','href="/home.css"').replace('<script src="/app.js"></script>','<script src="/home.js"></script><script type="module" src="/home-integration.js"></script>');if(mode==='PROJECT_RECOVERED')return text.replace('href="/styles.css"','href="/home.css"').replace('<script src="/project.js"></script>','<script src="/project.js"></script><script type="module" src="/project-integration.js"></script>');return text}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url||'/',`http://${req.headers.host||'127.0.0.1'}`);if(!['GET','HEAD'].includes(req.method||'')){res.writeHead(405,headers);return res.end();}
if(url.pathname==='/project.js'){const original=await readFile(path.join(root,'project-original.js'),'utf8');const adapted=original.replace('/service-worker-project.js','/service-worker.js');const body=Buffer.from(adapted);res.writeHead(200,{...headers,'content-type':'text/javascript; charset=utf-8','content-length':body.length,'x-agroway-recovery':'PR9-3d58-adapted-sw-only'});return req.method==='HEAD'?res.end():res.end(body)}
const doc=routeDocument(url.pathname);if(doc&&doc.mode!=='DIRECT'){const original=await readFile(path.join(root,doc.file),'utf8');const integrated=integrateRecoveredHtml(original,doc.mode);const body=Buffer.from(integrated);res.writeHead(200,{...headers,'content-type':'text/html; charset=utf-8','content-length':body.length,'x-agroway-recovery':'PR9-3d58-exact-source-integrated-runtime'});return req.method==='HEAD'?res.end():res.end(body)}
let rel=doc?.file||decodeURIComponent(url.pathname).replace(/^\/+/, '')||'home-original.html';let target=path.resolve(root,rel);if(!target.startsWith(path.resolve(root)))throw new Error('PATH_REJECTED');try{if((await stat(target)).isDirectory())target=path.join(target,'index.html')}catch{if(doc)target=path.join(root,doc.file);else throw new Error('NOT_FOUND')}const body=await readFile(target);res.writeHead(200,{...headers,'content-type':types[path.extname(target)]||'application/octet-stream','content-length':body.length});if(req.method==='HEAD')return res.end();res.end(body)}catch(error){const status=error.message==='NOT_FOUND'?404:500;const body=Buffer.from(JSON.stringify({error:error.message,trust:'DEMO_RECONSTRUCTED',canonicalMutated:false,executionState:'NOT_EXECUTED'}));res.writeHead(status,{...headers,'content-type':'application/json','content-length':body.length});res.end(body)}});
server.listen(port,'127.0.0.1',()=>console.log(`GREENATICS CONTROL v0.22 alpha9 http://127.0.0.1:${port}/control/authorization`));