export const FIELD_WEB_CAPABILITIES=['LOTS','TASKS','IRRIGATION','NUTRITION','PESTS','INVENTORY','OFFLINE_SYNC','FIELD_HOME','CROP_CYCLE_WORKSPACE','TASK_EVIDENCE_CAPTURE','INVENTORY_APPLICATION_WORKFLOW','MONITORING_INCIDENT_RESOLUTION','TRACEABILITY_PASSPORT_ASSEMBLY','HARVEST_SALE_SETTLEMENT_WORKSPACE','OFFLINE_SYNC_CONFLICT_REVIEW','ACCESS_ENTITLEMENTS_PORTABILITY','LOCAL_DEV_BACKEND_RUNTIME'] as const;
export * from './home-model.js';
export * from './crop-cycle-model.js';
export * from './task-evidence-model.js';
export * from './inventory-application-model.js';
export * from './monitoring-incident-model.js';
export * from './passport-assembly-model.js';
export * from './harvest-sale-settlement-model.js';
export * from './offline-sync-review-model.js';
export * from './access-portability-model.js';
export * from './local-dev-backend-model.js';
